name: qcards
description: "QCards is a digital flashcards app designed to help users study and retain information more effectively. With QCards, users can easily create and organize virtual flashcards to help them memorize and review important information.

Users can create custom decks of cards for a variety of subjects, from language vocabulary to exam preparation. Each card can feature a question or prompt on one side and the answer on the other. Users can also add images or audio files to their cards to help with visual or auditory learning.

One of the key features of QCards is its adaptive learning system, which tracks the user's progress and adjusts the difficulty of the flashcards accordingly. This ensures that users are challenged enough to learn, but not overwhelmed by too much information at once.

In addition, QCards offers a variety of study modes, including a timed mode and a self-assessment mode, allowing users to customize their study experience to fit their needs. The app also includes a variety of customization options, such as different fonts and colors, making it easy to personalize the flashcards to fit the user's preferences.

Whether you're studying for an exam or trying to learn a new language, QCards is the perfect tool to help you memorize and retain information more effectively."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  provider: ^6.0.5
  firebase_auth: ^4.2.4
  flip_card: ^0.7.0
  cloud_firestore: ^4.0.3
  google_sign_in: ^6.1.0
  font_awesome_flutter: ^10.4.0
  social_login_buttons: ^1.0.7
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  image: assets/images/QCard_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/